#pragma once

#include "hal_gpio.h"


// Analog pins
HAL_GPIO_PIN(A0, B, 2)
HAL_GPIO_PIN(A1, A, 5)
HAL_GPIO_PIN(A2, A, 4)

// Digital pins
HAL_GPIO_PIN(D0, A, 2)
HAL_GPIO_PIN(D1, A, 5)
HAL_GPIO_PIN(D2, A, 4)
HAL_GPIO_PIN(D3, B, 22)
HAL_GPIO_PIN(D4, B, 23)

// LED
HAL_GPIO_PIN(LED, B,  3)

// SPI
HAL_GPIO_PIN(SCK,  A, 5)
HAL_GPIO_PIN(MOSI, A, 4)
HAL_GPIO_PIN(CS,   B, 22)
HAL_GPIO_PIN(MISO, B, 23)

// UART
HAL_GPIO_PIN(TX, B, 22)
HAL_GPIO_PIN(RX, B, 23)

// I2C
HAL_GPIO_PIN(SDA, A, 12)
HAL_GPIO_PIN(SCL, A, 13)

// LCD
HAL_GPIO_PIN(COM0,  B,  9)
HAL_GPIO_PIN(COM1,  A,  6)
HAL_GPIO_PIN(COM2,  A,  7)
HAL_GPIO_PIN(COM3,  A,  8)
HAL_GPIO_PIN(SEG0,  A,  9)
HAL_GPIO_PIN(SEG1,  A, 14)
HAL_GPIO_PIN(SEG2,  A, 15)
HAL_GPIO_PIN(SEG3,  A, 16)
HAL_GPIO_PIN(SEG4,  A, 17)
HAL_GPIO_PIN(SEG5,  A, 18)
HAL_GPIO_PIN(SEG6,  A, 19)
HAL_GPIO_PIN(SEG7,  A, 20)
HAL_GPIO_PIN(SEG8,  A, 21)
HAL_GPIO_PIN(SEG9,  A, 22)
HAL_GPIO_PIN(SEG10, A, 23)
HAL_GPIO_PIN(SEG11, B, 11)

// Touch
HAL_GPIO_PIN(TOUCH_X0,  A, 11)
HAL_GPIO_PIN(TOUCH_X1,  A, 10)
HAL_GPIO_PIN(TOUCH_X22, A, 27)
HAL_GPIO_PIN(TOUCH_X21, A, 30)
HAL_GPIO_PIN(TOUCH_Y8,  A,  2)
HAL_GPIO_PIN(TOUCH_Y9,  A,  3)
HAL_GPIO_PIN(TOUCH_Y14, B,  8)
HAL_GPIO_PIN(TOUCH_Y23, A, 31)