#pragma once

#include "hal_gpio.h"
#include "spi.h"
#include "i2c.h"
#include "uart.h"

// Analog pins
HAL_GPIO_PIN(YOUT, A, 2)
HAL_GPIO_PIN(XOUT, A, 5)

// Buttons
HAL_GPIO_PIN(STOP_LIVE,  A, 1)
HAL_GPIO_PIN(PLAY_PAUSE, B, 2)
HAL_GPIO_PIN(RECORD,     A, 27)
HAL_GPIO_PIN(SLOWER,     A, 0)
HAL_GPIO_PIN(FASTER,     B, 3)

// LEDs
HAL_GPIO_PIN(LED_BLUE,   A, 12)
HAL_GPIO_PIN(LED_YELLOW, A, 13)
HAL_GPIO_PIN(LED_GREEN,  A, 14)
HAL_GPIO_PIN(LED_RED,    A, 15)

// Touch matrix
HAL_GPIO_PIN(X0, A, 16)
HAL_GPIO_PIN(X1, A, 17)
HAL_GPIO_PIN(X2, A, 18)
HAL_GPIO_PIN(X3, A, 19)
HAL_GPIO_PIN(X4, A, 20)
HAL_GPIO_PIN(X5, A, 21)
HAL_GPIO_PIN(X6, A, 22)
HAL_GPIO_PIN(X7, A, 23)
HAL_GPIO_PIN(Y0, A, 3)
HAL_GPIO_PIN(Y1, A, 6)
HAL_GPIO_PIN(Y2, A, 8)
HAL_GPIO_PIN(Y3, A, 9)
HAL_GPIO_PIN(Y4, A, 10)
HAL_GPIO_PIN(Y5, A, 11)
HAL_GPIO_PIN(Y6, B, 10)
HAL_GPIO_PIN(Y7, B, 11)

// UART
HAL_GPIO_PIN(TX,   B, 22)
HAL_GPIO_PIN(RX,   A, 23)
#define UART_SERCOM 5
#define UART_SERCOM_TXPO UART_TXPO_2
#define UART_SERCOM_RXPO UART_RXPO_3
