#pragma once

#include "hal_gpio.h"
#include "spi.h"
#include "i2c.h"
#include "uart.h"

// Analog pins

HAL_GPIO_PIN(AREF, A, 4)
HAL_GPIO_PIN(A0,   A, 2)
HAL_GPIO_PIN(A1,   A, 5)
HAL_GPIO_PIN(A2,   B, 8)
HAL_GPIO_PIN(A3,   B, 9)
HAL_GPIO_PIN(A4,   A, 6)
HAL_GPIO_PIN(A5,   A, 7)

#define HAL_GPIO_A0_DAC_CHANNEL 0
#define HAL_GPIO_A1_DAC_CHANNEL 1

#define HAL_GPIO_AREF_ADC_CHANNEL 4
#define HAL_GPIO_A0_ADC_CHANNEL 0
#define HAL_GPIO_A1_ADC_CHANNEL 5
#define HAL_GPIO_A2_ADC_CHANNEL 2
#define HAL_GPIO_A3_ADC_CHANNEL 3
#define HAL_GPIO_A4_ADC_CHANNEL 6
#define HAL_GPIO_A5_ADC_CHANNEL 7

#define HAL_GPIO_AREF_AC_CHANNEL 0
#define HAL_GPIO_A1_AC_CHANNEL 1
#define HAL_GPIO_A4_AC_CHANNEL 2
#define HAL_GPIO_A5_AC_CHANNEL 3

// Op amp pins (same as analog, but with different names for clarity)
HAL_GPIO_PIN(OPAMP0_POS, A, 6)
HAL_GPIO_PIN(OPAMP0_NEG, A, 2)
HAL_GPIO_PIN(OPAMP0_OUT, A, 7)
HAL_GPIO_PIN(OPAMP1_POS, B, 9)
HAL_GPIO_PIN(OPAMP1_OUT, B, 8)
HAL_GPIO_PIN(OPAMP2_POS, A, 5)
HAL_GPIO_PIN(OPAMP2_OUT, A, 4)

// Digital pins
HAL_GPIO_PIN(D0,   A, 21)
HAL_GPIO_PIN(D1,   B, 2)
HAL_GPIO_PIN(D4,   A, 16)
HAL_GPIO_PIN(D5,   A, 16)
HAL_GPIO_PIN(D6,   A, 17)
HAL_GPIO_PIN(D9,   A, 18)
HAL_GPIO_PIN(D10,  A, 19)
HAL_GPIO_PIN(D11,  A,  8)
HAL_GPIO_PIN(D12,  A,  9)
HAL_GPIO_PIN(D13,  A, 10)

#define HAL_GPIO_D1_ADC_CHANNEL 10
#define HAL_GPIO_D4_ADC_CHANNEL 11
#define HAL_GPIO_D11_ADC_CHANNEL 16
#define HAL_GPIO_D12_ADC_CHANNEL 17
#define HAL_GPIO_D13_ADC_CHANNEL 18

// LED
HAL_GPIO_PIN(LED,  A, 10)

// SPI
HAL_GPIO_PIN(SCK,  B, 11)
HAL_GPIO_PIN(MOSI, B, 10)
HAL_GPIO_PIN(MISO, A, 12)
#define SPI_SERCOM 4
#define SPI_SERCOM_DOPO SPI_DOPO_2_SCK_3
#define SPI_SERCOM_DIPO SPI_DIPO_0

// I2C
HAL_GPIO_PIN(SDA,  A, 22)
HAL_GPIO_PIN(SCL,  A, 23)
#define I2C_SERCOM 3

// UART
HAL_GPIO_PIN(TX,   B, 2)
HAL_GPIO_PIN(RX,   A, 21)
#define UART_SERCOM 5
#define UART_SERCOM_TXPO UART_TXPO_0
#define UART_SERCOM_RXPO UART_RXPO_3
