#pragma once

#include "hal_gpio.h"


// Analog pins
HAL_GPIO_PIN(AREF, A, 3)
HAL_GPIO_PIN(A0,   A, 2)
HAL_GPIO_PIN(A1,   A, 4)
HAL_GPIO_PIN(A2,   A, 5)
HAL_GPIO_PIN(A3,   A, 6)
HAL_GPIO_PIN(A4,   A, 7)
HAL_GPIO_PIN(D0,   A, 6)
HAL_GPIO_PIN(D1,   A, 7)

// Digital input
HAL_GPIO_PIN(BUTTON, A, 31)
HAL_GPIO_PIN(INTERRUPT, A, 30)

// Digital output
HAL_GPIO_PIN(LED,    A, 10) // alias for LED2
HAL_GPIO_PIN(LED0,   A, 14)
HAL_GPIO_PIN(LED1,   A, 15)
HAL_GPIO_PIN(LED2,   A, 10)
HAL_GPIO_PIN(LED3,   A, 11)
HAL_GPIO_PIN(LED6,   A, 16)
HAL_GPIO_PIN(LED7,   A, 17)
HAL_GPIO_PIN(EN_1V8, A, 27)

// SPI
HAL_GPIO_PIN(SCK,  A, 4)
HAL_GPIO_PIN(MOSI, A, 5)
HAL_GPIO_PIN(CS,   A, 6)
HAL_GPIO_PIN(MISO, A, 7)

// I2C
HAL_GPIO_PIN(SDA,  A, 22)
HAL_GPIO_PIN(SCL,  A, 23)
