CHIP = saml22
LDSCRIPT = saml22n18

DEFINES += \
  -D__SAML22J18A__ \

ifeq ($(FORCE_DISPLAY_TYPE), CUSTOM)
  DEFINES += -DFORCE_CUSTOM_LCD
endif

ifeq ($(FORCE_DISPLAY_TYPE), CLASSIC)
  DEFINES += -DFORCE_CLASSIC_LCD
endif
