name: Build

on:
  pull_request:
  push:
    branches-ignore:
      - gh-pages

jobs: 
  build:
    container:
      image: ghcr.io/armmbed/mbed-os-env:latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Work around CVE-2022-24765
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Compile blink app
        run: make
        working-directory: 'examples/blink'
