name: Build

on:
  pull_request:
  push:
    branches-ignore:
      - gh-pages

jobs: 
  build:
    container:
      image: ghcr.io/armmbed/mbed-os-env:latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Bulld DFU utility
        run: make
        working-directory: 'utils/dfu'
      - name: Validate changes on SAM D11
        run: make
        working-directory: 'tests/blink_samd11'
      - name: Validate changes on SAM D21
        run: make
        working-directory: 'tests/blink_samd21'
      - name: Validate changes on SAM D51
        run: make
        working-directory: 'tests/blink_samd51'
      - name: Validate changes on SAM L21
        run: make
        working-directory: 'tests/blink_saml21'
      - name: Validate changes on SAM L22
        run: make
        working-directory: 'tests/blink_saml22'
